name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer
      - name: Force SDK Install
        run: |
          # Installiamo l'SDK manualmente usando lo strumento ufficiale 'sdkmanager'
          mkdir -p ~/.android/sdk
          export ANDROID_HOME=~/.android/sdk
          # Questo comando forza l'installazione di build-tools che includono aidl
          echo "y" | sudo /usr/lib/android-sdk/tools/bin/sdkmanager "build-tools;33.0.1" "platforms;android-33"
      - name: Build with Buildozer
        env:
          ANDROID_HOME: /home/runner/.android/sdk
        run: |
          buildozer android debug
