name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kivy/buildozer-action@master
        with:
          buildozer_version: stable
